# Generated by Django 5.2.4 on 2025-07-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_course_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
