# Generated by Django 5.2.4 on 2025-07-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_course_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
