# Generated by Django 5.2.4 on 2025-07-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_course_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='example-slug',null=True, blank=True),
            preserve_default=False,
        ),
    ]
